services:
  database:
    image: "postgres:18.0-alpine3.22"
    user: "${UID}:${GID}"
    container_name: ${POSTGRES_HOST}
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
    volumes:
      - ./postgresql_db_data:/var/lib/postgresql/18/data
      - ./src/main/resources/postgres/postgres.compiled.conf:/etc/postgresql/postgresql.conf
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -p $${POSTGRES_PORT}"]
      interval: 5s
      timeout: 5s
      retries: 5
  wildfly:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    environment:
      - POSTGRES_HOST
      - POSTGRES_DB
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./src/main/resources/wildfly/standalone.compiled.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml
      - ./target:/opt/jboss/wildfly/standalone/deployments/
    networks:
      - backend
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy

networks:
  backend: {}