services:
  database:
    image: "postgres:18.0-alpine3.22"
    container_name: ${POSTGRES_HOST}
    environment:
      - POSTGRES_HOST
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      # - ./app/src/main/resources/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql_db_data:/var/lib/postgresql/18/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
  wildfly:
    image: quay.io/wildfly/wildfly:28.0.0.Final-jdk20
    environment:
      - POSTGRES_HOST
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      # - ./app/src/main/resources/wildfly/standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml
      - ./target:/opt/jboss/wildfly/standalone/deployments/
      # - ./public/app/src/main/typescript:/opt/jboss/wildfly/resources/app
      # - ./public/jsf-component/src/main/resources/META-INF/resources/itmo:/opt/jboss/wildfly/resources/itmo
    networks:
      - backend
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy

networks:
  backend: {}